package strategy

// MarketSnapshot represents a snapshot of the market at a given time.
type MarketSnapshot struct {
	Instrument   string
	MidPrice     float64
	Bid          float64
	Ask          float64
	SpreadBps    float64
	TimestampMs  int64
	Volume24h    float64
	FundingRate  float64
	OpenInterest float64
}

// StrategyDecision represents a single decision/order generated by a strategy.
type StrategyDecision struct {
	Action      string                 // "place_order" or "noop"
	Instrument  string
	Side        string                 // "buy" or "sell"
	Size        float64
	LimitPrice  float64
	OrderType   string                 // "Gtc" (rest on book), "Ioc" (cross spread), "Alo" (maker-only), "Market", "StopMarket", "TakeProfitMarket"
	Meta        map[string]interface{} // Extra metadata
}

// StrategyContext provides rich context passed to strategies each tick.
type StrategyContext struct {
	Snapshot         MarketSnapshot
	PositionQty      float64 // net position in base asset (positive for long, negative for short)
	PositionNotional float64 // notional USD exposure
	UnrealizedPnL    float64
	RealizedPnL      float64
	ReduceOnly       bool    // from risk manager
	SafeMode         bool
	RoundNumber      int
	Meta             map[string]interface{}
}

// BaseStrategy is the interface all strategies must implement.
type BaseStrategy interface {
	ID() string
	OnTick(snapshot MarketSnapshot, ctx *StrategyContext) []StrategyDecision
}
